User.create(id: 0, name: "テストユーザー", place: "North Carolina", email: "test@exam.com", password: "19920818", admin: "false")

admin_id = Rails.application.credentials.admin[:user_id]

# song(vocal)
Song.create(title:"Blue Moon of Kentucky", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Blue Night", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Blue Ridge Cabin Home", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Can't You Hear Me Calling", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Close by", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Come Back Darling", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Country Road", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Dark Hollow", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Don’t You Call My Name", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Down the Road", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Fireball Mail", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Hold Whatcha Got", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"How Mountain Girls Can Love", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I Am a Pilgrim", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I'll Never Shed Another Tear", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I'll Stay Around", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I'm Going Back to Old Kentucky", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I Saw the Light", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"It's Mighty Dark to Travel", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I've Waited as Long as I Can", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"I Wonder Where You Are Tonight", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Keep on the Sunny Side", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Kentucky Waltz", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Little Cabin Home on the Hill", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Little Maggie", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Lonesome Pine", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Lonesome Road Blues", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Long Journey Home", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Love Me Darling Just Tonight", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Love Please Come Home", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Molly And Tenbrooks", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"My Home Across the Blue Ridge Mountains", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"My Little Georgia Rose", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"My Little Girl in Tennessee", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"My Old Kentucky Home", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"My Rose of Old Kentucky", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Nine Pound Hammer", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Ocean of Diamond", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Old Home Place", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Old Home Town", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"On And On", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"One Tear", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"On My Way Back to the Old Home", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Out in the Cold World", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Pain in My Heart", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Pig in a Pen", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Rocky Top", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Rollin' My Sweet Baby's Arm", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Salty Dog Blues", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sitting on Top of the World", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Some Old Day", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sugar Coated Love", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sunny Side of Life", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sunny Side of Mountain", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sweetheart You Done Me Wrong", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Take Me in a Lifeboat", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Take This Hammer", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"The Old Home", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Think of What You've Done", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Toy Heart", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Uncle Pen", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Used to Be", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Wall of Time", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"We'll Meet Again Sweetheart", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"White House Blues", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Whose Shoulder Will You Cry on", jam: 0, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Why Did You Wander", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Will The Circle Be Unbroken", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Y'all Come", jam: 1, standard: 1, beginner: 0, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"You Are My Sunshine", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Your Love Is Like a Flower", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 0, practice_songs_count: 0, user_id: admin_id)

# song(instrumental)
Song.create(title:"Arkansas Traveler", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Beaumont Rag", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Big Mon", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Big Sandy River", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Big Sciota", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Bill Cheatham", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Billy in the Low Ground", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Black Berry Blossom", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Bluegrass Breakdown", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Black Mountain Rag", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Boil'em Cabbage Down", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Boston Boy", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Brown County Breakdown", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Bugle Call Rag", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Cherokee Shuffle", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Clinch Mountain Backstep", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Cripple Creek", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Daybreak in Dixie", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Dear Old Dixie", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Devil's Dream", jam: 0, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Dixie Breakdown", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Down Yonder", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Earl's Breakdown", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"East Tennessee Blues", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Faded Love", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Flint Hill Special", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Foggy Mountain Breakdown", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Foggy Mountain Rock", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Foggy Mountain Special", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Golden Slipper", jam: 0, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Gold Rush", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Ground Speed", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Home Sweet Home", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"John Hardy", jam: 0, standard: 1, beginner: 1, vocal: 1, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"John Henry", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Monroe's Hornpipe", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"New Camptown Races", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Old Joe Clerk", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Red Haird Boy", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Red Wing", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Pick Away", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Pike County Breakdown", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Raw Hide", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Road to Columbus", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Roanoke", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sally Goodin'", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Salt Creek", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Shenandoah Breakdown", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Shuckin' the Corn", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Sled Ride", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Soldier's Joy", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"St. Anne's Reel", jam: 1, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Theme Time", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Turkey in the Straw", jam: 1, standard: 1, beginner: 1, vocal: 1, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Washington County", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Wheel Hoss", jam: 0, standard: 1, beginner: 0, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
Song.create(title:"Whiskey Before Breakfast", jam: 1, standard: 1, beginner: 1, vocal: 0, instrumental: 1, practice_songs_count: 0, user_id: admin_id)
